### ISSUE TITLE
Why onSnepClientReady() execute so many times？

### ISSUE THREAD

**Issue by niguang1** [NXPNFCLinux/linux_libnfc-nci_examples#3]
I run the P2P_example on two boards,and modify one of them as receiver by delete "isPeerDevicePresent = 1;" in function onSnepClientReady(),and then,both of them display so many "Peer device arrived" and "Peer device left" ?
Does the device mode  shut down automatically after a while?

**Comment by jgeslin** [comment]
This change (removing `isPeerDevicePresent = 1;` in function `onSnepClientReady`) should not impact peer device discovery/lost. By the way The best way to set your device to only be able to receive NDEF data is simply by not registering SNEP Client callback (remove call to `nfcSnep_registerClientCallback `function).

In order to deeper analyze what is on-going, please enable logs by setting parameters NXPLOG_xxx_LOGLEVEL to value 0x03 within /usr/local/etc/libnfc-nxp-init.conf file.

**Comment by niguang1** [comment]
I found out that As long as you don't call receiver‘s  nfcSnep_stopServer(), the sender's onSnepClientReady() is called time after time through debugging.And i think that's unreasonable ，Maybe there should be three function :

- onSnepClientReady()     just called once to report when server is arrived
- onSnepClientClosed()   just called once to report when server is lefted
- isSnepClientReady()     Query client status when needed

How did you like it?

**Comment by jgeslin** [comment]
I don't get your point.
Basically onSnepClientReady() is called each time a remote peer device is detected and exposing SNEP capabilities (running a SNEP server) while onSnepClientClosed() is called each time this peer device is lost.
If you see those callback functions called several time during a session, you may experienced P2P disconnection/connection. This must be checked looking to the libnfc-nci traces.
